services:
  - type: web
    name: marketly-luxury-ecommerce
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: AUTH_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_DISPLAY_NAME
        sync: false
      - key: MONGODB_URI
        sync: false
