import { Category, Brand, Product, PromotionBanner, AuditLog, MediaAsset } from '../types';

export const initialCategories: Category[] = [
  {
    id: 'cat_fashion',
    name: 'Fashion',
    slug: 'fashion',
    iconName: 'Shirt',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&q=80&w=400',
    itemCount: 20450,
    featured: true,
  },
  {
    id: 'cat_electronics',
    name: 'Electronics',
    slug: 'electronics',
    iconName: 'Headphones',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=400',
    itemCount: 15200,
    featured: true,
  },
  {
    id: 'cat_beauty',
    name: 'Beauty',
    slug: 'beauty',
    iconName: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=400',
    itemCount: 8400,
    featured: true,
  },
  {
    id: 'cat_home',
    name: 'Home Decor',
    slug: 'home-decor',
    iconName: 'Armchair',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&q=80&w=400',
    itemCount: 12100,
    featured: true,
  },
  {
    id: 'cat_grocery',
    name: 'Grocery',
    slug: 'grocery',
    iconName: 'ShoppingBasket',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=400',
    itemCount: 9500,
    featured: false,
  },
  {
    id: 'cat_sports',
    name: 'Sports',
    slug: 'sports',
    iconName: 'Dumbbell',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=400',
    itemCount: 6800,
    featured: false,
  },
  {
    id: 'cat_watches',
    name: 'Watches',
    slug: 'watches',
    iconName: 'Watch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=400',
    itemCount: 4200,
    featured: true,
  },
  {
    id: 'cat_computing',
    name: 'Computing',
    slug: 'computing',
    iconName: 'Laptop',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=400',
    itemCount: 7600,
    featured: true,
  },
];

export const initialBrands: Brand[] = [
  { id: 'brand_apple', name: 'Apple', slug: 'apple' },
  { id: 'brand_sony', name: 'Sony', slug: 'sony' },
  { id: 'brand_nike', name: 'Nike', slug: 'nike' },
  { id: 'brand_samsung', name: 'Samsung', slug: 'samsung' },
  { id: 'brand_logitech', name: 'Logitech', slug: 'logitech' },
  { id: 'brand_keychron', name: 'Keychron', slug: 'keychron' },
  { id: 'brand_rolex', name: 'Rolex', slug: 'rolex' },
  { id: 'brand_nordic', name: 'Nordic Living', slug: 'nordic-living' },
];

export const initialProducts: Product[] = [
  {
    id: '1',
    name: "Men's Air Sneakers Running Shoes",
    slug: 'mens-air-sneakers-running-shoes',
    sku: 'NK-AIR-001',
    shortDescription: 'Ultra-lightweight breathable cushion running shoes for performance athletics and street style.',
    description: 'Engineered with reactive air-cushion foam soles, precision flyknit breathable upper, and ergonomic arch support. Perfect for marathon training, gym workouts, or all-day casual wear with unmatched comfort and grip.',
    category: 'Fashion',
    subcategory: 'Footwear',
    brand: 'Nike',
    price: 59.99,
    compareAtPrice: 79.99,
    discountPercent: 25,
    rating: 4.8,
    reviewCount: 1234,
    mainImage: '/src/assets/images/sneakers_white_air_1790933024489.jpg',
    galleryImages: [
      '/src/assets/images/sneakers_white_air_1790933024489.jpg',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800',
    ],
    variants: [
      { id: 'v1_1', sku: 'NK-AIR-001-41-WHT', name: 'White / 41 EU', attributes: { size: '41', color: 'Pure White' }, price: 59.99, compareAtPrice: 79.99, inventory: 15 },
      { id: 'v1_2', sku: 'NK-AIR-001-42-WHT', name: 'White / 42 EU', attributes: { size: '42', color: 'Pure White' }, price: 59.99, compareAtPrice: 79.99, inventory: 28 },
      { id: 'v1_3', sku: 'NK-AIR-001-43-WHT', name: 'White / 43 EU', attributes: { size: '43', color: 'Pure White' }, price: 59.99, compareAtPrice: 79.99, inventory: 8 },
      { id: 'v1_4', sku: 'NK-AIR-001-44-WHT', name: 'White / 44 EU', attributes: { size: '44', color: 'Pure White' }, price: 59.99, compareAtPrice: 79.99, inventory: 0 },
    ],
    inventory: 51,
    tags: ['Sneakers', 'Running', 'Shoes', 'Men', 'Sale'],
    isFeatured: true,
    isBestSeller: false,
    specifications: {
      'Upper Material': 'Engineered Flyknit Mesh',
      'Sole Material': 'Reactive Air Cushion Rubber',
      'Closure Type': 'Lace-Up',
      'Weight': '280g (per shoe)',
      'Origin': 'Vietnam',
    },
    materials: '100% Recycled polyester mesh upper with natural rubber outsole',
    careInstructions: 'Spot clean with lukewarm soapy water and soft brush. Air dry only.',
    shippingInfo: 'Standard 2-4 business days. Free shipping on orders over $49.',
    returnPolicy: '30-day hassle-free return policy. Unworn items in original packaging.',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: '2',
    name: 'Premium Wireless Earbuds Pro',
    slug: 'premium-wireless-earbuds-pro',
    sku: 'SNY-WF-1000XM5',
    shortDescription: 'Industry-leading Active Noise Cancellation with high-resolution wireless LDAC audio.',
    description: 'Immerse yourself in crystal-clear audio with custom-tuned dynamic drivers, dual feedback microphones for active noise cancelling, and IPX4 sweat resistance. Up to 36 hours total battery life with fast Qi wireless charging.',
    category: 'Electronics',
    subcategory: 'Audio',
    brand: 'Sony',
    price: 69.99,
    compareAtPrice: 99.99,
    discountPercent: 20,
    rating: 4.9,
    reviewCount: 2631,
    mainImage: '/src/assets/images/earbuds_pro_white_1790933037064.jpg',
    galleryImages: [
      '/src/assets/images/earbuds_pro_white_1790933037064.jpg',
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=800',
    ],
    variants: [
      { id: 'v2_1', sku: 'SNY-WF-WHT', name: 'Glacier White', attributes: { color: 'Glacier White' }, price: 69.99, compareAtPrice: 99.99, inventory: 42 },
      { id: 'v2_2', sku: 'SNY-WF-BLK', name: 'Midnight Onyx', attributes: { color: 'Midnight Onyx' }, price: 69.99, compareAtPrice: 99.99, inventory: 19 },
    ],
    inventory: 61,
    tags: ['Earbuds', 'Audio', 'Noise Cancelling', 'Wireless', 'Bluetooth'],
    isFeatured: true,
    isBestSeller: false,
    specifications: {
      'Bluetooth Version': '5.3 with LE Audio',
      'Battery Life': '8h per charge + 24h charging case',
      'Water Resistance': 'IPX4 Splash Proof',
      'Noise Cancellation': 'Active Dual-Chip ANC',
      'Charging Port': 'USB-C + Qi Wireless',
    },
    materials: 'Matte antimicrobial polycarbonate casing with medical-grade silicone ear tips',
    careInstructions: 'Wipe with dry microfiber cloth. Keep charging contacts clean and dry.',
    shippingInfo: 'Fast dispatch within 24 hours. Express delivery available.',
    returnPolicy: '30-day money-back guarantee.',
    createdAt: '2026-01-12T11:30:00Z',
  },
  {
    id: '3',
    name: 'Smart Watch Series Ultra Titanium',
    slug: 'smart-watch-series-ultra-titanium',
    sku: 'APL-WCH-ULTRA',
    shortDescription: 'Aerospace-grade titanium smart watch with always-on retina display and comprehensive health tracking.',
    description: 'Precision crafted for exploration, fitness, and daily luxury. Features ECG heart monitoring, blood oxygen sensor, dual-frequency GPS tracking, cellular connectivity, and water resistance up to 100 meters.',
    category: 'Watches',
    subcategory: 'Smart Watches',
    brand: 'Apple',
    price: 149.99,
    compareAtPrice: 249.99,
    discountPercent: 40,
    rating: 4.95,
    reviewCount: 3840,
    mainImage: '/src/assets/images/smartwatch_flash_deal_1790933014371.jpg',
    galleryImages: [
      '/src/assets/images/smartwatch_flash_deal_1790933014371.jpg',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=800',
    ],
    variants: [
      { id: 'v3_1', sku: 'APL-WCH-49-BLK', name: '49mm Space Black / Trail Loop', attributes: { size: '49mm', strap: 'Black Trail Loop' }, price: 149.99, compareAtPrice: 249.99, inventory: 14 },
      { id: 'v3_2', sku: 'APL-WCH-49-ORG', name: '49mm Titanium / Alpine Orange', attributes: { size: '49mm', strap: 'Alpine Orange' }, price: 149.99, compareAtPrice: 249.99, inventory: 11 },
    ],
    inventory: 25,
    tags: ['Watch', 'Smartwatch', 'Flash Deal', 'Titanium', 'Health'],
    isFeatured: true,
    isBestSeller: true,
    isFlashDeal: true,
    specifications: {
      'Case Material': 'Aerospace Grade Titanium',
      'Display': 'Always-On Sapphire Crystal OLED 3000 nits',
      'Battery Life': 'Up to 72 hours in Low Power Mode',
      'Water Resistance': '100m ISO standard 22810',
      'Sensors': 'ECG, SpO2, Skin Temp, Depth Gauge',
    },
    materials: 'Grade 5 Titanium bezel, Sapphire crystal front, Ceramic back',
    careInstructions: 'Rinse with fresh water after saltwater exposure.',
    shippingInfo: 'Complimentary insured courier delivery.',
    returnPolicy: '30-day inspection period.',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: '4',
    name: 'MacBook Air M2 13-inch 512GB',
    slug: 'macbook-air-m2-13-inch',
    sku: 'APL-MBA-M2-512',
    shortDescription: 'Strikingly thin design with blazing fast Apple M2 silicon, 13.6-inch Liquid Retina display.',
    description: 'The ultra-portable workstation with 8-core CPU, 10-core GPU, 16GB unified memory, and 512GB ultra-fast SSD. Up to 18 hours of battery life with silent fanless thermal architecture.',
    category: 'Computing',
    subcategory: 'Laptops',
    brand: 'Apple',
    price: 1099.99,
    compareAtPrice: 1349.99,
    discountPercent: 18,
    rating: 4.9,
    reviewCount: 1200,
    mainImage: '/src/assets/images/laptop_pro_slim_1790933051456.jpg',
    galleryImages: [
      '/src/assets/images/laptop_pro_slim_1790933051456.jpg',
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800',
    ],
    variants: [
      { id: 'v4_1', sku: 'APL-MBA-MIDNIGHT', name: '16GB / 512GB Midnight', attributes: { color: 'Midnight', storage: '512GB' }, price: 1099.99, compareAtPrice: 1349.99, inventory: 8 },
      { id: 'v4_2', sku: 'APL-MBA-STARLIGHT', name: '16GB / 512GB Starlight', attributes: { color: 'Starlight', storage: '512GB' }, price: 1099.99, compareAtPrice: 1349.99, inventory: 12 },
      { id: 'v4_3', sku: 'APL-MBA-SPACEGRAY', name: '16GB / 512GB Space Gray', attributes: { color: 'Space Gray', storage: '512GB' }, price: 1099.99, compareAtPrice: 1349.99, inventory: 5 },
    ],
    inventory: 25,
    tags: ['Laptop', 'Apple', 'Computing', 'M2', 'Best Seller'],
    isFeatured: true,
    isBestSeller: true,
    specifications: {
      'Processor': 'Apple M2 8-core CPU / 10-core GPU',
      'Memory': '16GB Unified High-Bandwidth RAM',
      'Storage': '512GB PCIe NVMe SSD',
      'Display': '13.6-inch Liquid Retina Display with True Tone',
      'Weight': '1.24 kg (2.7 lbs)',
    },
    materials: '100% Recycled aluminum unibody enclosure',
    careInstructions: 'Clean screen with 70% isopropyl alcohol wipe and microfiber cloth.',
    shippingInfo: 'Free signature-required express delivery.',
    returnPolicy: '14-day Apple authorized return & 1-year global warranty.',
    createdAt: '2026-01-05T08:00:00Z',
  },
  {
    id: '5',
    name: 'iPhone 15 Pro Max 256GB',
    slug: 'iphone-15-pro-max-256gb',
    sku: 'APL-IP15PM-256',
    shortDescription: 'Forged in titanium with groundbreaking A17 Pro chip, customizable Action button, 5x telephoto camera.',
    description: 'The ultimate smartphone experience featuring a durable and lightweight aerospace-grade titanium design with textured matte-glass back. Dynamic Island, 48MP main camera system with computational photonic engine, and USB-C with USB 3 speeds.',
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'Apple',
    price: 999.99,
    compareAtPrice: 1299.99,
    discountPercent: 22,
    rating: 4.85,
    reviewCount: 1200,
    mainImage: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=80&w=800',
    ],
    variants: [
      { id: 'v5_1', sku: 'APL-IP15PM-NT', name: 'Natural Titanium 256GB', attributes: { color: 'Natural Titanium', storage: '256GB' }, price: 999.99, compareAtPrice: 1299.99, inventory: 16 },
      { id: 'v5_2', sku: 'APL-IP15PM-BL', name: 'Blue Titanium 256GB', attributes: { color: 'Blue Titanium', storage: '256GB' }, price: 999.99, compareAtPrice: 1299.99, inventory: 9 },
    ],
    inventory: 25,
    tags: ['Phone', 'Smartphone', 'Apple', 'Titanium', 'Best Seller'],
    isFeatured: false,
    isBestSeller: true,
    specifications: {
      'Chipset': 'A17 Pro with 6-core GPU',
      'Camera': '48MP Main + 12MP Ultra-wide + 12MP 5x Telephoto',
      'Display': '6.7-inch Super Retina XDR OLED 120Hz ProMotion',
      'Durability': 'Ceramic Shield front, IP68 water resistance',
    },
    materials: 'Grade 5 Titanium frame with Corning Ceramic Shield glass',
    careInstructions: 'Protect with tempered glass shield and MagSafe case.',
    shippingInfo: 'Insured next-day express courier dispatch.',
    returnPolicy: '30-day exchange policy.',
    createdAt: '2026-01-08T08:00:00Z',
  },
  {
    id: '6',
    name: 'Air Fryer 4.5L Digital Touch Display',
    slug: 'air-fryer-digital-display',
    sku: 'HME-AF-45L',
    shortDescription: '360° rapid hot air circulation with 8 one-touch presets and non-stick dishwasher-safe basket.',
    description: 'Crispy fried food with up to 85% less oil. Built-in smart temperature sensor, capacitive LED touch control panel, and shake reminder for golden culinary perfection.',
    category: 'Home Decor',
    subcategory: 'Kitchen Appliances',
    brand: 'Nordic Living',
    price: 75.99,
    compareAtPrice: 99.99,
    discountPercent: 24,
    rating: 4.7,
    reviewCount: 862,
    mainImage: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=800',
    ],
    variants: [
      { id: 'v6_1', sku: 'HME-AF-BLK', name: 'Matte Carbon Black', attributes: { color: 'Matte Carbon Black' }, price: 75.99, compareAtPrice: 99.99, inventory: 34 },
    ],
    inventory: 34,
    tags: ['Kitchen', 'Home', 'Appliances', 'Cooking', 'Best Seller'],
    isFeatured: false,
    isBestSeller: true,
    specifications: {
      'Capacity': '4.5 Liters / 4.8 Quarts',
      'Power': '1500 Watts 220-240V',
      'Temperature Range': '80°C - 200°C',
      'Timer': 'Up to 60 minutes with auto-shutoff',
    },
    materials: 'BPA-free heat resistant housing and Teflon-free ceramic basket',
    careInstructions: 'Basket is dishwasher safe. Wipe exterior with damp sponge.',
    shippingInfo: 'Standard 2-3 day delivery in reinforced packaging.',
    returnPolicy: '30-day warranty against manufacturing defects.',
    createdAt: '2026-01-02T12:00:00Z',
  },
  {
    id: '7',
    name: 'Modern 3-Seater Fabric Sofa',
    slug: 'modern-3-seater-fabric-sofa',
    sku: 'FRN-SF-3STR',
    shortDescription: 'Scandinavian minimalist deep-seat lounge sofa with stain-resistant textured linen upholstery.',
    description: 'Handcrafted solid kiln-dried oak timber frame with high-density resilient pocket spring cushions. Generous seating depth with removable and machine-washable cushion covers for timeless lounge luxury.',
    category: 'Home Decor',
    subcategory: 'Furniture',
    brand: 'Nordic Living',
    price: 299.99,
    compareAtPrice: 379.99,
    discountPercent: 20,
    rating: 4.6,
    reviewCount: 542,
    mainImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&q=80&w=800',
    ],
    variants: [
      { id: 'v7_1', sku: 'FRN-SF-CHARCOAL', name: 'Charcoal Slate', attributes: { color: 'Charcoal Slate' }, price: 299.99, compareAtPrice: 379.99, inventory: 7 },
      { id: 'v7_2', sku: 'FRN-SF-BEIGE', name: 'Oatmeal Beige', attributes: { color: 'Oatmeal Beige' }, price: 299.99, compareAtPrice: 379.99, inventory: 4 },
    ],
    inventory: 11,
    tags: ['Sofa', 'Living Room', 'Furniture', 'Nordic', 'Home'],
    isFeatured: false,
    isBestSeller: true,
    specifications: {
      'Dimensions': '210cm W x 92cm D x 84cm H',
      'Frame': 'FSC Certified Solid Hardwood',
      'Fabric Martindale': '45,000 rubs (commercial grade)',
      'Assembly': 'Tool-free leg attachment in 5 minutes',
    },
    materials: 'High-resilience foam, pocket coils, solid oak legs, linen-blend fabric',
    careInstructions: 'Vacuum regularly with upholstery brush attachment. Fabric spot-cleaner safe.',
    shippingInfo: 'White-glove room-of-choice freight delivery.',
    returnPolicy: '30-day home trial period.',
    createdAt: '2026-01-04T14:00:00Z',
  },
  {
    id: '8',
    name: 'Keychron Q1 Pro Wireless Mechanical Keyboard',
    slug: 'keychron-q1-pro-wireless-mechanical-keyboard',
    sku: 'KCR-Q1P-RED',
    shortDescription: '75% fully aluminum custom mechanical keyboard with hot-swappable switches and south-facing RGB.',
    description: 'CNC machined 6063 aluminum body with double-gasket acoustic mounting, double-shot KSA PBT keycaps, Bluetooth 5.1 multi-device connectivity, and customizable QMK/VIA key mapping support.',
    category: 'Computing',
    subcategory: 'Keyboards',
    brand: 'Keychron',
    price: 189.99,
    compareAtPrice: 219.99,
    discountPercent: 14,
    rating: 4.9,
    reviewCount: 412,
    mainImage: 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=800',
    ],
    variants: [
      { id: 'v8_1', sku: 'KCR-Q1P-RED-BLK', name: 'Carbon Black / Red Linear', attributes: { color: 'Carbon Black', switches: 'Gateron Jupiter Red (Linear)' }, price: 189.99, compareAtPrice: 219.99, inventory: 18 },
      { id: 'v8_2', sku: 'KCR-Q1P-BRN-SLV', name: 'Silver Gray / Brown Tactile', attributes: { color: 'Silver Gray', switches: 'Gateron Jupiter Brown (Tactile)' }, price: 189.99, compareAtPrice: 219.99, inventory: 14 },
    ],
    inventory: 32,
    tags: ['Keyboard', 'Mechanical', 'Computing', 'Keychron', 'Gaming'],
    isFeatured: true,
    isBestSeller: false,
    specifications: {
      'Layout': '75% Exploded with Rotary Encoder Knob',
      'Connectivity': 'Bluetooth 5.1 / Type-C Wired (1000Hz polling)',
      'Switches': 'Pre-lubed Gateron Jupiter Mechanical',
      'Battery': '4000mAh rechargeable lithium-polymer (up to 300 hours)',
    },
    materials: 'Full CNC anodized aluminum case, brass screw-in stabilizers',
    careInstructions: 'Use included switch and keycap puller for maintenance.',
    shippingInfo: 'Dispatched within 24 hours.',
    returnPolicy: '30-day money-back guarantee.',
    createdAt: '2026-01-14T10:00:00Z',
  },
];

export const initialBanners: PromotionBanner[] = [
  {
    id: 'ban_hero',
    title: 'Everything You Need, All in One Place',
    subtitle: 'Discover millions of products from top brands and trusted sellers. Best prices, premium quality & unbeatable service.',
    badge: 'PREMIUM QUALITY, PREMIUM YOU.',
    ctaText: 'Shop Now',
    ctaLink: '/shop',
    image: '/src/assets/images/marketly_hero_showcase_1790933000831.jpg',
    active: true,
    position: 'hero',
  },
  {
    id: 'ban_flash_deal',
    title: 'Flash Deal - Limited Time Offer',
    subtitle: 'Smart Watch Series Ultra Titanium at special price $149.99 ~~$249.99~~',
    badge: 'FLASH DEAL',
    ctaText: 'Shop the Deal',
    ctaLink: '/product/smart-watch-series-ultra-titanium',
    image: '/src/assets/images/smartwatch_flash_deal_1790933014371.jpg',
    bgColor: '#1D4ED8',
    active: true,
    position: 'flash_deal',
  },
  {
    id: 'ban_dual_left',
    title: 'Summer Collection',
    subtitle: 'Up to 50% Off On Fashion & Accessories',
    badge: 'LIMITED EDITION',
    ctaText: 'Shop Now',
    ctaLink: '/shop?category=Fashion',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800',
    bgColor: '#F59E0B',
    active: true,
    position: 'promotional_dual_left',
  },
  {
    id: 'ban_dual_right',
    title: 'Home Essentials For Better Living',
    subtitle: 'Up to 40% Off On Home & Kitchen',
    badge: 'NEW ARRIVALS',
    ctaText: 'Shop Now',
    ctaLink: '/shop?category=Home+Decor',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800',
    bgColor: '#3B82F6',
    active: true,
    position: 'promotional_dual_right',
  },
];

export const initialReviews: Record<string, Product['rating'] extends number ? any[] : any[]> = {
  '1': [
    {
      id: 'rev_1_1',
      productId: '1',
      userId: 'usr_cust_2',
      userName: 'Emily Johnson',
      rating: 5,
      comment: 'Super lightweight and the air cushion is extremely soft on morning runs. Perfect fit!',
      isVerifiedPurchase: true,
      createdAt: '2026-02-14T09:12:00Z',
    },
    {
      id: 'rev_1_2',
      productId: '1',
      userId: 'usr_cust_3',
      userName: 'David Miller',
      rating: 5,
      comment: 'The flyknit mesh breathes so well. Excellent quality and fast shipping from Marketly!',
      isVerifiedPurchase: true,
      createdAt: '2026-02-10T14:30:00Z',
    },
  ],
  '2': [
    {
      id: 'rev_2_1',
      productId: '2',
      userId: 'usr_cust_4',
      userName: 'Sarah Jenkins',
      rating: 5,
      comment: 'The noise cancellation completely blocks out subway and office chatter. Battery life easily lasts all day.',
      isVerifiedPurchase: true,
      createdAt: '2026-02-18T18:20:00Z',
    },
  ],
  '3': [
    {
      id: 'rev_3_1',
      productId: '3',
      userId: 'usr_cust_5',
      userName: 'Tanvir Ahmed',
      rating: 5,
      comment: 'The titanium finish is gorgeous. GPS tracking on runs in Gulshan is pinpoint accurate.',
      isVerifiedPurchase: true,
      createdAt: '2026-02-20T10:15:00Z',
    },
  ],
};

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log_1',
    actor: 'Mahim Haque (Super Admin)',
    action: 'Flash Deal Activated',
    resource: 'Smart Watch Series Ultra Titanium',
    details: 'Price reduced from $249.99 to $149.99 (40% discount)',
    timestamp: '2026-10-02T02:00:00Z',
  },
  {
    id: 'log_2',
    actor: 'Mahim Haque (Super Admin)',
    action: 'Promotion Banner Updated',
    resource: 'Hero Banner',
    details: 'Uploaded new high-res commercial render asset',
    timestamp: '2026-10-02T01:30:00Z',
  },
  {
    id: 'log_3',
    actor: 'Mahim Haque (Super Admin)',
    action: 'Inventory Rebalanced',
    resource: 'MacBook Air M2 13-inch',
    details: 'Stock verified at 25 units across variants',
    timestamp: '2026-10-01T22:15:00Z',
  },
];

export const initialMediaAssets: MediaAsset[] = [
  {
    id: 'med_1',
    name: 'marketly_hero_showcase.jpg',
    url: '/src/assets/images/marketly_hero_showcase_1790933000831.jpg',
    format: 'JPG',
    size: 245000,
    dimensions: '1600x1200',
    uploadedAt: '2026-10-02T02:23:25Z',
    folder: 'Banners',
  },
  {
    id: 'med_2',
    name: 'smartwatch_flash_deal.jpg',
    url: '/src/assets/images/smartwatch_flash_deal_1790933014371.jpg',
    format: 'JPG',
    size: 198000,
    dimensions: '1200x1200',
    uploadedAt: '2026-10-02T02:23:36Z',
    folder: 'Products',
  },
  {
    id: 'med_3',
    name: 'sneakers_white_air.jpg',
    url: '/src/assets/images/sneakers_white_air_1790933024489.jpg',
    format: 'JPG',
    size: 184000,
    dimensions: '1200x1200',
    uploadedAt: '2026-10-02T02:23:48Z',
    folder: 'Products',
  },
  {
    id: 'med_4',
    name: 'earbuds_pro_white.jpg',
    url: '/src/assets/images/earbuds_pro_white_1790933037064.jpg',
    format: 'JPG',
    size: 176000,
    dimensions: '1200x1200',
    uploadedAt: '2026-10-02T02:24:01Z',
    folder: 'Products',
  },
  {
    id: 'med_5',
    name: 'laptop_pro_slim.jpg',
    url: '/src/assets/images/laptop_pro_slim_1790933051456.jpg',
    format: 'JPG',
    size: 220000,
    dimensions: '1200x1200',
    uploadedAt: '2026-10-02T02:24:19Z',
    folder: 'Products',
  },
];
